### ISSUE TITLE
Display warning if user has JS disabled

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#324]
Currently if user opens our pages with JS disabled in their browser, a blank page is displayed.

It would be more user-friendly if we displayed a warning like "Looks like you have JavaScript disabled in your browser. Please enable it to enjoy our service.".

**Comment by indeyets** [comment]
fixed by #365

**Comment by smallq-git** [comment]
Looks ok now in Chrome:
![image](https://cloud.githubusercontent.com/assets/7983303/7783797/9e191fda-0157-11e5-97fe-546975f2918c.png)

Still don't see anything in IE10 but JS seems to be working there anyway despite being turned off.
