### ISSUE TITLE
Ban: still can see blocked user's posts inside groups

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#499]

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/1f5be0374c43b8e6c14ccaee1b48c200b849ef89

**Comment by smallq-git** [comment]
Still happens, as evidenced by this screenshot (testo had banned testuser1 yet still sees testuser1's posts in cheese group and is able to comment):
![image](https://cloud.githubusercontent.com/assets/7983303/8393329/f966a3d0-1d13-11e5-9fdb-dd01b5d126c7.png)

However, the post stops being visible after page reload.

**Comment by epicmonkey** [comment]
Is it a home feed page?

**Comment by smallq-git** [comment]
On both homefeed and group feed pages. Screenshot above was taken on homefeed page, and here's screenshot from group feed page:
![image](https://cloud.githubusercontent.com/assets/7983303/8393987/9d63f784-1d2e-11e5-9ae0-8be2510c752e.png)

Note that banning user (testo) is able to comment and see comments on the post. Banned user (testuser1) can only see their own comments on the post.

**Comment by smallq-git** [comment]
still happens in real-time. disappears after page reload

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/89a246ba25eb15a1e8996f1f91a94fb8b3c93a93

**Comment by clbn** [comment]
Still can reproduce on micropeppa (realtime part only):

Pre-condition:
1. User-A and User-B are both subscribed to Group-C.
2. User-B has banned User-A.

Steps:
1. Open Group-C's feed as User-A in one browser.
2. Open Group-C's feed as User-B in another browser.
3. Post to the group as User-A.

Expected:
User-B does not see any new posts show up in the Group-C.

Actual:
User-B sees new posts from User-A on Group-C's page (as realtime updates). After reload they dissappear.

**Comment by clbn** [comment]
@epicmonkey Still can reproduce it with the latest ^ script. I suppose pepyatka/pepyatka-server@023b81e90dbe76f2f65d01b32fba80bfd37affbe didn't fix it.

**Comment by epicmonkey** [comment]
Could be, yes. (sigh) will take a look.
